### ISSUE TITLE
import errors. could you please help whats wrong here

### ISSUE THREAD

**Issue by malviyamukul** [ecabuk/vlf#1]
when i run python3 main.py 

it throws me errors like this

raceback (most recent call last):
  File "main.py", line 13, in <module>
    from views.main import MainView
  File "/home/my/Desktop/vlf-master/views/main.py", line 10, in <module>
    from views.spectrum import SpectrumView
  File "/home/my/Desktop/vlf-master/views/spectrum.py", line 7, in <module>
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
  File "/home/my/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 17, in <module>
    from .backend_qt5agg import NavigationToolbar2QTAgg
  File "/home/my/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/home/my/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/my/.local/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/my/.local/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/my/.local/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 111, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class

**Comment by malviyamukul** [comment]
hey solve the above issue but now this error shows 

 raise SerialException("Port is already open.")
serial.serialutil.SerialException: Port is already open.

**Comment by malviyamukul** [comment]
solved the above issue but now this port error comes in.

my@my-desktop:~/Desktop/vlf-master$ sudo python3 main.py Traceback (most recent call last):
  File "main.py", line 55, in <module>
    inclinometer.start_readings()
  File "/home/my/Desktop/vlf-master/inclinometer.py", line 58, in start_readings
    setup_port()
  File "/home/my/Desktop/vlf-master/inclinometer.py", line 94, in setup_port
    PORT.open()
  File "/home/my/.local/lib/python3.5/site-packages/serial/serialposix.py", line 261, in open
    raise SerialException("Port is already open.")
serial.serialutil.SerialException: Port is already open.

**Comment by ecabuk** [comment]
Hi,

The software is as is. I am not providing support for it, sorry.
